### PR TITLE
Add rng related methods

### PR DESCRIPTION
**Pull request by knshnb**
Add a public method to set rng seeds.
Also, I added the `CMAwM._rng` property for backward compatibility.

### CODE REVIEW

**Comment by knshnb** [comment]
@c-bata Could you take a look when you have time?

**Review by c-bata — COMMENTED** [review]
Could you also add `reseed_rng` in SepCMA class?

**Comment by knshnb** [comment]
Oh, sure, updated!

**Review by c-bata — APPROVED** [review]
LGTM!

**Pull request merged**
