### PR TITLE
Fix correction of out-of-range discrete params of `CMAwM`

### PR DESCRIPTION
**Pull request by knshnb**
A discrete version of https://github.com/CyberAgentAILab/cmaes/pull/134.

### CODE REVIEW

**Comment by knshnb** [comment]
@nomuramasahir0 Let me confirm one point related to this PR.
When we have a discrete parameter of step 1 with `bounds = [1.0, 3.0]`, should we sample the continuous version of the parameter from `[1.0, 3.0]` or `[0.5, 3.5]`?

**Comment by nomuramasahir0** [comment]
@knshnb 
To be consistent with the continuous case in the current implementation, I think it may be better to use `[1.0, 3.0]` ver also in the discrete case.
But to be honestly, I'm not so sure whether this is reasonable, and so this opinion may change in the future.
In the near future, I would like to empirically investigate reasonable box constraint handling in the continuous and discrete case in the CMA-ES.

**Review by c-bata — APPROVED** [review]
> To be consistent with the continuous case in the current implementation, I think it may be better to use [1.0, 3.0] ver also in the discrete case.

Thank you for your input! LGTM.

**Comment by knshnb** [comment]
Thanks for the reply and review!
Then, let me proceed in this direction and delete the method `_repair_continuous_params`, which is no longer necessary.

**Review by c-bata — APPROVED** [review]

**Comment by c-bata** [comment]
Let me merge this PR since we reached a consensus with @nomuramasahir0. Thank you for the input.

**Pull request merged**
